title: ETES 2021 Amsterdam
description: Information about the ETES 2021 in Amsterdam
markdown: kramdown
#theme: jekyll-theme-cayman
remote_theme: etes2021/cayman-blog
google_analytics: G-5WL1J60HTS
url: "https://etes2021.eu"

header_page_refs: ['home', 'tournament']
